name: Deploy Production Database Structure

on:
    workflow_dispatch:
    push: 
        branches: [ "master" ]
    
jobs:
    deploy:
        runs-on: [ self-hosted, windows ]
        steps:
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: cd BOTrasedV3.Database && dotnet build BOTrasedV3.Database.sqlproj --configuration Release
        - name: Deploy
          uses: azure/sql-action@v2
          with:
            connection-string: ${{ secrets.PROD_DB_CONNECTION_STRING }}
            action: 'publish'
            path: 'bin/Debug/BOTrasedV3.Database.dacpac'
